#!/bin/bash
#
# A start script for Freevo applications which may be used by init. Init
# has the ability to watchdog processes and restart them if they fail.
# To run this from init you may edit /etc/inittab and add a line with the 
# syntax:  1-4 letter identifyer:runlevels to run at:respawn:command
#
# Please read the inittab man page (man inittab) to understand this example:
# FV1:2345:respawn:/path/to/freevo_init <helper_name>
#
# Using this script with no helper_name argument will start Freevo itself.
#
# Typing 'init q' will tell init to reread inittab so it can start this 
# for you.
#
# Once init is running this for you and you simply wish to restart it then you
# only need to kill the process and init will start it back up.  You may easily
# kill the process by running the record_server script with the stop argument:
#
# freevo <helper_name> stop
#
# There is a file called boot_config which can be found in the boot/ 
# directory of Freevo.  This file should be copied to /etc/freevo/boot_config
# and edited to suit your needs.  It contains valuable environment variables
# for Freevo applications.
#
# $Id$

# Get startup config file
test -f /etc/freevo/boot_config || exit 0
. /etc/freevo/boot_config

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin

$FREEVO_HOME/freevo $1 2>&1 > /dev/null

# Sleep for some seconds to keep things sane if Freevo fails to start.
sleep 6
