#!/bin/sh

# freevo - the main entry point to the whole suite of applications
#
# $Id$
#

# Is runapp present? If not it needs to be compiled
if ! test -a runapp ; then
    echo ./runapp not found! You must compile freevo, see INSTALL.
    exit
fi

# First check if the runtime is installed
if test -a freevo_rt/freevo_rt ; then
    echo Found the runtime, will use it.
    # Prevent the linker from using other libraries than the ones
    # in freevo_rt
    export LD_PRELOAD=`cat freevo_rt/preloads`
    # Execute using the runtime
    #freevo_rt/ld-linux.so.2 freevo_rt/freevo_rt main.py $*
    freevo_rt/freevo_rt main.py $*
    # Make sure all children are killed
    sleep 1
    killall -9 freevo_rt/ld-linux.so.2
    exit
fi

echo Runtime not found, starting using Python.

python startup.py $*
