#! /bin/sh
#
# Enhanced boot script for freevo
#
# $Id$

# Get startup config file
test -f /etc/freevo/boot_config || exit 0
. /etc/freevo/boot_config

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin:/usr/games
DAEMON=$FREEVO_HOME/freevo
NAME=freevo
DESC=freevo

test -f $DAEMON || exit 0

#set -e

case "$1" in
  start)
	echo -n "Starting $DESC: "
	export SDL_NOKEYBOARD=true
	export SDL_VIDEODRIVER=fbcon
	(cd $FREEVO_HOME && $DAEMON >> $FREEVO_LOG 2>&1 &)
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC: "
        killall -9 freevo_rt &> /dev/null
        killall -9 freevo_xwin &> /dev/null
        killall -9 mplayer &> /dev/null
        kill -9 `pgrep -f "python main.py" -d" "` &> /dev/null
        kill -9 `pgrep -f "python rc_client" -d" "` &> /dev/null
	echo "$NAME."
	echo -n "Releasing the VT: "
	$VTRELEASE
	echo "vtrelease"
	;;
  #reload)
  #;;
  restart|force-reload)
	#
	#	If the "reload" option is implemented, move the "force-reload"
	#	option to the "reload" entry above. If not, "force-reload" is
	#	just the same as "restart".
	#
	echo "Restarting..."
	$0 stop
	sleep 1
	$0 start
	;;
  *)
	N=/etc/init.d/$NAME
	# echo "Usage: $N {start|stop|restart|reload|force-reload}" >&2
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
