# config for the webserver

import config

TIMEFORMAT = config.TV_TIMEFORMAT
GUIDE_INTERVAL = config.WWW_GUIDE_INTERVAL
GUIDE_INTERVAL = config.WWW_GUIDE_INTERVAL
GUIDE_PRECISION = config.WWW_GUIDE_PRECISION
STYLESHEET = config.WWW_STYLESHEET
JAVASCRIPT = config.WWW_JAVASCRIPT
ENCODING = config.encoding
USERS = config.WWW_USERS
PORT = config.WWW_PORT
